apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: todoapp
spec:
      containers:
      - name: web
        image: janakiramm/todo-app
        ports:
        - containerPort: 3000
